"""empty message

Revision ID: 3ab336f54d9f
Revises: 33a81aa1075c
Create Date: 2023-08-02 12:07:37.823657

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "3ab336f54d9f"
down_revision = "33a81aa1075c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
